name: Parse single IPK filename
description: "Extract pkg, version, and arch from a single .ipk filename"
author: jackie264
branding:
  icon: package
  color: green

inputs:
  file:
    description: "Path to .ipk file (glob allowed)"
    required: true
  output_dir:
    description: "Directory to write parsed metadata (default: .)"
    required: false
    default: "."

outputs:
  pkg:
    description: "Package name"
    value: ${{ steps.run.outputs.pkg }}
  ver:
    description: "Package version"
    value: ${{ steps.run.outputs.ver }}
  ver_full:
    description: "Package version"
    value: ${{ steps.run.outputs.ver_full }}
  arch:
    description: "Package architecture"
    value: ${{ steps.run.outputs.arch }}

runs:
  using: composite
  steps:
    - name: Run parser
      id: run
      shell: bash
      env:
        IPK_FILE: ${{ inputs.file }}
        OUTPUT_DIR: ${{ inputs.output_dir }}
      run: |
        chmod +x "${GITHUB_ACTION_PATH}/parse-ipk-file.sh"
        "${GITHUB_ACTION_PATH}/parse-ipk-file.sh"
