name: Parse single IPK filename
description: Extract pkg, version, and arch from a single .ipk filename
author: jackie264
branding:
  icon: package
  color: green

inputs:
  file:
    description: Path to the .ipk file (absolute or workspace-relative)
    required: true

outputs:
  pkg:
    description: Package name
    value: ${{ steps.run.outputs.pkg }}
  ver:
    description: Package version
    value: ${{ steps.run.outputs.ver }}
  arch:
    description: Package architecture
    value: ${{ steps.run.outputs.arch }}

runs:
  using: composite
  steps:
    - name: Load parser
      shell: bash
      run: |
        source "${GITHUB_ACTION_PATH}/parse_ipk.sh"

    - name: Run parser
      id: run
      shell: bash
      run: |
        FILE="${{ inputs.file }}"
        fname="$(basename "$FILE")"
        eval "$(parse_ipk_filename "$fname")"
        echo "pkg=$pkg" >> $GITHUB_OUTPUT
        echo "ver=$ver" >> $GITHUB_OUTPUT
        echo "arch=$arch" >> $GITHUB_OUTPUT
